{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubernetes-event-exporter.serviceAccountName" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
{{- end }}
